/* settings.h
 *
 * Copyright (C) 2014-2026 wolfSSL Inc.  All rights reserved.
 *
 * This file is part of wolfSSH.
 *
 * Contact licensing@wolfssl.com with any questions or comments.
 *
 * https://www.wolfssl.com
 */


/*
 * The settings header provides a method for developers to provide the
 * internal preprocessor defines that the configure script provides to
 * environments that do not use the configure script.
 */


#ifndef _WOLFSSH_SETTINGS_H_
#define _WOLFSSH_SETTINGS_H_

#include <wolfssh/visibility.h>

#ifdef WOLFSSL_USER_SETTINGS
    #include "user_settings.h"
#elif defined(USE_HAL_DRIVER) && !defined(HAVE_CONFIG_H)
    /* STM Configuration File (generated by CubeMX) */
    #include "wolfSSL.I-CUBE-wolfSSH_conf.h"
#endif

#if defined(WOLFSSH_ZEPHYR) && defined(CONFIG_WOLFSSH_SETTINGS_FILE)
    #include CONFIG_WOLFSSH_SETTINGS_FILE
#endif

#ifdef __cplusplus
extern "C" {
#endif


/* user settings here */
#ifndef WMALLOC_USER
    #define USE_WOLFSSH_MEMORY  /* default memory handlers */
#endif /* WMALLOC_USER */

/* SFTP requires storehandle when fatfs is in use */
#ifdef WOLFSSH_FATFS
    #define WOLFSSH_STOREHANDLE
#endif

#if defined (_WIN32)
    #define USE_WINDOWS_API
    #define _CRT_SECURE_NO_WARNINGS
#endif

#ifdef WOLFSSL_NUCLEUS
    #ifndef WOLFSSH_STOREHANDLE
    #define WOLFSSH_STOREHANDLE
    #endif
#endif

#ifdef MICROCHIP_MPLAB_HARMONY
    #ifndef WOLFSSH_STOREHANDLE
    #define WOLFSSH_STOREHANDLE
    #endif
#endif  

#ifdef FREESCALE_MQX
    #define NO_STDIO_FILESYSTEM
    #ifndef WOLFSSH_STOREHANDLE
        #define WOLFSSH_STOREHANDLE
    #endif

    #ifdef WOLFSSH_SCP
        #error wolfSSH SCP not ported to MQX yet
    #endif
#endif

#if defined(WOLFSSH_SCP) && defined(NO_WOLFSSH_SERVER)
    #error only SCP server side supported
#endif

/* Detect if ECC needs RNG */
#if !defined(HAVE_WC_ECC_SET_RNG) && \
    defined(ECC_TIMING_RESISTANT) && (!defined(HAVE_FIPS) || \
    (!defined(HAVE_FIPS_VERSION) || (HAVE_FIPS_VERSION != 2))) && \
    !defined(HAVE_SELFTEST)
    /* Enable use of wc_ecc_set_rng */
    #define HAVE_WC_ECC_SET_RNG
#endif

/* Maximum number of prompts in one request / response transaction for
 * Keyboard-Interactive authentication.
 */

#if defined(WOLFSSH_KEYBOARD_INTERACTIVE) && !defined(WOLFSSH_MAX_PROMPTS)
    #define WOLFSSH_MAX_PROMPTS 64
#endif

#ifdef __cplusplus
}
#endif

#endif /* _WOLFSSH_SETTINGS_H_ */

